version: "3.8"

services:
  tika:
    image: apache/tika:latest
    container_name: tika-server
    restart: unless-stopped
    # Expose Tika's default port 9998 to the host
    ports:
      - "9998:9998"
    networks:
      - bigdata_network

networks:
  bigdata_network:
    driver: bridge
