
version: "3.8"

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181 server.2=zookeeper2:2888:3888;2182 server.3=zookeeper3:2888:3888;2183
    networks:
      - bigdata_network
    volumes:
      - ./zookeeper-conf/zoo.cfg:/conf/zoo.cfg
      - ../.env/zookeeper_data:/var/lib/zookeeper/data
      - ../.env/zookeeper_txn_logs:/var/lib/zookeeper/log
    ports:
      - "2181:2181" # Client port
      - "2888:2888" # Leader election port
      - "3888:3888" # Leader communication port

  zookeeper2:
    image: zookeeper:latest
    container_name: zookeeper2
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181 server.2=zookeeper2:2888:3888;2182 server.3=zookeeper3:2888:3888;2183
    networks:
      - bigdata_network
    volumes:
      - ./zookeeper-conf/zoo.cfg:/conf/zoo.cfg
      - ../.env/zookeeper2_data:/var/lib/zookeeper/data
      - ../.env/zookeeper2_txn_logs:/var/lib/zookeeper/log
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"

  zookeeper3:
    image: zookeeper:latest
    container_name: zookeeper3
    restart: always
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181 server.2=zookeeper2:2888:3888;2182 server.3=zookeeper3:2888:3888;2183
    networks:
      - bigdata_network
    volumes:
      - ./zookeeper-conf/zoo.cfg:/conf/zoo.cfg
      - ../.env/zookeeper3_data:/var/lib/zookeeper/data
      - ../.env/zookeeper3_txn_logs:/var/lib/zookeeper/log
    ports:
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"

  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    restart: unless-stopped
    environment:
      - HTTP_PORT=8800
    ports:
      - "8800:8800"
    networks:
      - bigdata_network
    depends_on:
      - zookeeper

  controller-1:
    image: apache/kafka:latest
    container_name: controller-1
    restart: unless-stopped
    networks:
      - bigdata_network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  controller-2:
    image: apache/kafka:latest
    container_name: controller-2
    restart: unless-stopped
    networks:
      - bigdata_network
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  controller-3:
    image: apache/kafka:latest
    container_name: controller-3
    restart: unless-stopped
    networks:
      - bigdata_network
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  broker-1:
    image: apache/kafka:latest
    container_name: broker-1
    restart: unless-stopped
    networks:
      - bigdata_network
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-2:
    image: apache/kafka:latest
    container_name: broker-2
    restart: unless-stopped
    networks:
      - bigdata_network
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-3:
    image: apache/kafka:latest
    container_name: broker-3
    restart: unless-stopped
    networks:
      - bigdata_network
    ports:
      - 49092:9092
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:19092,PLAINTEXT_HOST://localhost:49092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    container_name: kafka-rest-proxy
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: broker-1:19092,broker-2:19092,broker-3:19092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_HOST_NAME: kafka-rest-proxy # Internal network name
    networks:
      - bigdata_network
    depends_on:
      - broker-1
      - broker-2
      - broker-3
      - zookeeper

  hadoop-namenode:
    image: apache/hadoop:3.4.1
    container_name: hadoop-namenode
    networks:
      - bigdata_network
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop-config:/etc/hadoop
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
      - HADOOP_HOME=/opt/hadoop
    command: ["/opt/hadoop/bin/hdfs", "datanode"]

  hadoop-datanode:
    image: apache/hadoop:3.4.1
    container_name: hadoop-datanode
    networks:
      - bigdata_network
    depends_on:
      - hadoop-namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./hadoop-config:/etc/hadoop
    ports:
      - "9864:9864"
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
      - HADOOP_HOME=/opt/hadoop
    command: ["/opt/hadoop/bin/hdfs", "datanode"]

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    networks:
      - bigdata_network
    environment:
      - SPARK_MODE=master
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8080:8080"
      - "7077:7077"
    command:
      ["/bin/bash", "-c", "/opt/spark/sbin/start-master.sh --host spark-master"]
    depends_on:
      - hadoop-namenode
      - hadoop-datanode

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    networks:
      - bigdata_network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"
    command:
      [
        "/bin/bash",
        "-c",
        "/opt/spark/sbin/start-worker.sh spark://spark-master:7077",
      ]
    depends_on:
      - spark-master

  solr:
    image: solr:latest
    container_name: solr
    restart: unless-stopped
    networks:
      - bigdata_network
    command: solr -f -c -z zookeeper:2181,zookeeper2:2181,zookeeper3:2181
    # command: solr create_collection -c mycollection -shards 2 -replicationFactor 2 -z zookeeper:2181,zookeeper2:2181,zookeeper3:2181
    ports:
      - "8983:8983"
    environment:
      # 1) Increase Solr's JVM heap size (example: 4GB)
      SOLR_HEAP: "4g"
      # 2) Enable basic authentication via JVM system properties.
      SOLR_OPTS: > 
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -Dsolr.authentication.class=org.apache.solr.security.BasicAuthPlugin
        -Dsolr.basicAuth.username=solr
        -Dsolr.basicAuth.password=123456789
        -Dsolr.allow.unsafe.resourceloading=true
        -Dsolr.max.boolean.clauses=4096
    volumes:
      - solr1_data:/var/solr
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3
    # healthcheck:
      # test:
        # ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/info/system"]
      # interval: 10s
      # timeout: 5s
      # retries: 5

  solr2:
    image: solr:latest
    container_name: solr2
    restart: unless-stopped
    networks:
      - bigdata_network
    command: solr -f -c -z zookeeper:2181,zookeeper2:2181,zookeeper3:2181
    # command: solr create_collection -c mycollection -shards 2 -replicationFactor 2 -z zookeeper:2181,zookeeper2:2181,zookeeper3:2181
    ports:
      - "8984:8983"
    environment:
      # 1) Increase Solr's JVM heap size (example: 4GB)
      SOLR_HEAP: "4g"
      # 2) Enable basic authentication via JVM system properties.
      SOLR_OPTS: > 
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -Dsolr.authentication.class=org.apache.solr.security.BasicAuthPlugin
        -Dsolr.basicAuth.username=solr
        -Dsolr.basicAuth.password=123456789
        -Dsolr.allow.unsafe.resourceloading=true
        -Dsolr.max.boolean.clauses=4096
    volumes:
      - solr2_data:/var/solr
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3
    # healthcheck:
      # test:
        # ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/info/system"]
      # interval: 10s
      # timeout: 5s
      # retries: 5

  solr3:
    image: solr:latest
    container_name: solr3
    restart: unless-stopped
    networks:
      - bigdata_network
    command: solr -f -c -z zookeeper:2181,zookeeper2:2181,zookeeper3:2181
    # command: solr create_collection -c mycollection -shards 2 -replicationFactor 2 -z zookeeper:2181,zookeeper2:2181,zookeeper3:2181
    ports:
      - "8985:8983"
    environment:
      # 1) Increase Solr's JVM heap size (example: 4GB)
      SOLR_HEAP: "4g"
      # 2) Enable basic authentication via JVM system properties.
      SOLR_OPTS: > 
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -Dsolr.authentication.class=org.apache.solr.security.BasicAuthPlugin
        -Dsolr.basicAuth.username=solr
        -Dsolr.basicAuth.password=123456789
        -Dsolr.allow.unsafe.resourceloading=true
        -Dsolr.max.boolean.clauses=4096
    volumes:
      - solr3_data:/var/solr
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3
    # healthcheck:
      # test:
        # ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/info/system"]
      # interval: 10s
      # timeout: 5s
      # retries: 5

  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi
    restart: unless-stopped
    networks:
      - bigdata_network
    ports:
      - "8088:8088"
    environment:
      # - NIFI_WEB_HTTPS_PORT=8444
      - NIFI_WEB_HTTP_PORT=8088
      - NIFI_WEB_PROXY_HOST=192.168.94.129:8088
      # - NIFI_CLUSTER_IS_NODE=true
      # - NIFI_CLUSTER_NODE_ADDRESS=nifi
      # - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      # - NIFI_ZOOKEEPER_CONNECT_STRING=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      # - NIFI_SENSITIVE_PROPS_KEY=BoX3C0AzSltsqwFLnnD+LO2iLbbo7+iZgOQfH93M7iM=
    volumes:
      # - ./nifi-conf/nifi.properties.template:/opt/nifi/nifi-current/conf/nifi.properties.template
      # - ./nifi-conf/authorizers.xml:/opt/nifi/nifi-current/conf/authorizers.xml
      # - ./nifi-conf/login-identity-providers.xml:/opt/nifi/nifi-current/conf/login-identity-providers.xml
      - ./certs:/opt/nifi/certs
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3

  nifi_2.0.0:
    image: apache/nifi:latest
    container_name: nifi_2.0.0
    restart: unless-stopped
    # environment:
      # NIFI_WEB_HTTP_HOST: 192.168.160.128 # Set the hostname/IP NiFi should use
      # NIFI_WEB_HTTP_PORT: 8087
      # Add other necessary env vars for enabling HTTPS, keystore/truststore paths, passwords, etc.
      # Example (might vary based on image version and setup):
      # NIFI_SECURITY_KEYSTORE: /path/inside/container/to/keystore.jks
      # NIFI_SECURITY_KEYSTORE_TYPE: JKS
      # NIFI_SECURITY_KEYSTORE_PASSWD: your_keystore_password
      # NIFI_SECURITY_TRUSTSTORE: /path/inside/container/to/truststore.jks
      # NIFI_SECURITY_TRUSTSTORE_TYPE: JKS
      # NIFI_SECURITY_TRUSTSTORE_PASSWD: your_truststore_password
    networks:
      - bigdata_network
    ports:
      - "8443:8443"
      # - "8087:8087"
    depends_on:
      - zookeeper

  mongo1:
    image: mongo:8.0.3
    container_name: mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456789 # Must match primary
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - ../.env/mongodb_keyfile/mongodb-keyfile:/data/configdb/keyfile
    networks:
      - bigdata_network
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--auth",
        "--keyFile",
        "/data/configdb/keyfile",
        "--bind_ip_all",
      ]
    depends_on:
      - zookeeper
      - zookeeper2
      - zookeeper3

  mongo2:
    image: mongo:8.0.3
    container_name: mongo2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456789 # Must match primary
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
      - ../.env/mongodb_keyfile/mongodb-keyfile:/data/configdb/keyfile
    networks:
      - bigdata_network
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--auth",
        "--keyFile",
        "/data/configdb/keyfile",
        "--bind_ip_all",
      ]
    depends_on:
      - mongo1

  mongo3:
    image: mongo:8.0.3
    container_name: mongo3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456789 # Must match primary
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
      - ../.env/mongodb_keyfile/mongodb-keyfile:/data/configdb/keyfile
    networks:
      - bigdata_network
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--auth",
        "--keyFile",
        "/data/configdb/keyfile",
        "--bind_ip_all",
      ]
    depends_on:
      - mongo1

    # Redis service
  redis:
    image: redis:latest # or another stable version
    container_name: redis
    restart: always
    networks:
      - bigdata_network
    ports:
      - "6379:6379"

  backend:
    image: ysp3_backend:10
    container_name: backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=Search
      # - MONGO_HOST=192.168.94.129:27017,192.168.94.129:27018,192.168.94.129:27019
      - MONGO_HOST=mongo1:27017,mongo2:27018,mongo3:27019
      # - MONGO_HOST=${HOST_IP}:27017,${HOST_IP}:27018,${HOST_IP}:27019
      - REPLICA_SET_NAME=rs0
      - AUTH_SOURCE=admin
      - READ_PREFERENCE=secondaryPreferred
      # - MONGO_TLS=false
      # - MONGO_TLS_CERT_FILE=./cert/cert.pem
      - SOLR_HOST=http://solr:8983/solr
      - SOLR_AUTH_USER=solr
      - SOLR_AUTH_PASSWORD=123456789
      # - SOLR_QUERY=http://192.168.94.129:8983/solr/investigations/select
      # - SOLR_COLLECTIONS_LIST=http://${HOST_IP}:8983/solr/admin/collections?action=LIST&wt=json
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NIFI_BASE_URL=http://nifi:8088/nifi-api
      - NIFI_USERNAME=nifiUser
      - NIFI_PASSWORD=nifiPass
      - ZOOKEEPER_CONNECTION_STRING=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
    volumes:
      - ./:/usr/src/app
    networks:
      - bigdata_network

  frontend:
    image: ysp3_frontend:10
    container_name: frontend-dev
    restart: unless-stopped
    ports:
      - "3000:80"
    # environment:
      # - API_BASE_URL=http://192.168.94.129:5000/api
    volumes:
      - ./frontend:/app
    networks:
      - bigdata_network
    depends_on:
      - backend

volumes:
  hadoop_namenode:
  hadoop_datanode:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongodb_keyfile:
  solr1_data:
  solr2_data:
  solr3_data:

networks:
  bigdata_network:
    driver: bridge
